#!/bin/bash

testappDir=$LAB_HOUSE_DIR/testapp/
resultsDir=$LAB_HOUSE_DIR/results/
decodedAppd=.msg.raw.json
rr=RR

num=fs3859
diff ${testappDir}${num}${decodedAppd} ${resultsDir}${num}${decodedAppd}
[ $? -ne 0 ] && exit 1

exit 0
