#!/bin/bash
function error
{
    echo "Error! $1"
    exit 1
}
function checkRC
{
    rc=$1
    running=$2
    if [ $rc -ne 0 ];then
        error "$running failed with return value: $rc"
    fi
}
function genReport
{
    echo "__STF__:$1=$2"
}
exit 1
